export const siteIndex = [
    { url: 'https://ru.wikipedia.org', title: 'Википедия (RU)', description: 'Русскоязычная энциклопедия с открытым контентом.', keywords: ['Википедия', 'Wikipedia', 'энциклопедия', 'ru'] },
    { url: 'https://habr.com', title: 'Хабр', description: 'Платформа для IT-специалистов, статьи и новости.', keywords: ['Хабр', 'Habr', 'IT', 'технологии'] },
    { url: 'https://stackoverflow.com', title: 'Stack Overflow', description: 'Сообщество для программистов, вопросы и ответы.', keywords: ['Stack Overflow', 'программирование', 'код'] },
    { url: 'https://google.com', title: 'Google', description: 'Поисковая система и сервисы.', keywords: ['Google', 'Гугл', 'поиск'] },
    { url: 'https://youtube.com', title: 'YouTube', description: 'Видеохостинг и платформа для контента.', keywords: ['YouTube', 'Ютуб', 'видео'] },
    { url: 'https://facebook.com', title: 'Facebook', description: 'Социальная сеть для общения.', keywords: ['Facebook', 'Фейсбук', 'соцсеть'] },
    { url: 'https://instagram.com', title: 'Instagram', description: 'Платформа для фото и видео.', keywords: ['Instagram', 'Инстаграм', 'фото'] },
    { url: 'https://whatsapp.com', title: 'WhatsApp', description: 'Мессенджер для общения.', keywords: ['WhatsApp', 'Ватсап', 'мессенджер'] },
    { url: 'https://x.com', title: 'X', description: 'Социальная сеть для коротких сообщений.', keywords: ['X', 'Twitter', 'Твиттер', 'соцсеть'] },
    { url: 'https://wikipedia.org', title: 'Wikipedia', description: 'Многоязычная энциклопедия.', keywords: ['Wikipedia', 'Википедия', 'энциклопедия'] },
    { url: 'https://chatgpt.com', title: 'ChatGPT', description: 'AI-ассистент от OpenAI.', keywords: ['ChatGPT', 'ЧатГПТ', 'AI', 'ИИ'] },
    { url: 'https://reddit.com', title: 'Reddit', description: 'Сообщества и обсуждения.', keywords: ['Reddit', 'Реддит', 'форум'] },
    { url: 'https://yahoo.com', title: 'Yahoo', description: 'Поиск и новости.', keywords: ['Yahoo', 'Яху', 'поиск'] },
    { url: 'https://yahoo.co.jp', title: 'Yahoo Japan', description: 'Японский портал и поиск.', keywords: ['Yahoo Japan', 'Яху Япония', 'поиск'] },
    { url: 'https://amazon.com', title: 'Amazon', description: 'Онлайн-магазин и облачные сервисы.', keywords: ['Amazon', 'Амазон', 'магазин'] },
    { url: 'https://yandex.ru', title: 'Яндекс', description: 'Поиск и сервисы для России.', keywords: ['Яндекс', 'Yandex', 'поиск', 'Яндекс Поиск'] },
    { url: 'https://baidu.com', title: 'Baidu', description: 'Китайская поисковая система.', keywords: ['Baidu', 'Байду', 'поиск'] },
    { url: 'https://tiktok.com', title: 'TikTok', description: 'Платформа для коротких видео.', keywords: ['TikTok', 'ТикТок', 'видео'] },
    { url: 'https://netflix.com', title: 'Netflix', description: 'Стриминговый сервис для фильмов.', keywords: ['Netflix', 'Нетфликс', 'фильмы'] },
    { url: 'https://microsoftonline.com', title: 'Microsoft Online', description: 'Облачные сервисы Microsoft.', keywords: ['Microsoft Online', 'Майкрософт', 'облако'] },
    { url: 'https://linkedin.com', title: 'LinkedIn', description: 'Социальная сеть для профессионалов.', keywords: ['LinkedIn', 'Линкедин', 'работа'] },
    { url: 'https://live.com', title: 'Live', description: 'Сервисы Microsoft, включая почту.', keywords: ['Live', 'Майкрософт', 'почта'] },
    { url: 'https://naver.com', title: 'Naver', description: 'Южнокорейский поиск и портал.', keywords: ['Naver', 'Навер', 'поиск'] },
    { url: 'https://dzen.ru', title: 'Дзен', description: 'Платформа для контента и новостей.', keywords: ['Дзен', 'Yandex Zen', 'новости'] },
    { url: 'https://office.com', title: 'Microsoft Office', description: 'Онлайн-офисные приложения.', keywords: ['Microsoft Office', 'Офис', 'документы'] },
    { url: 'https://microsoft.com', title: 'Microsoft', description: 'Официальный сайт Microsoft.', keywords: ['Microsoft', 'Майкрософт', 'технологии'] },
    { url: 'https://xvideos.com', title: 'XVideos', description: 'Платформа для взрослого контента.', keywords: ['XVideos', 'взрослый контент'] },
    { url: 'https://pinterest.com', title: 'Pinterest', description: 'Платформа для идей и вдохновения.', keywords: ['Pinterest', 'Пинтерест', 'идеи'] },
    { url: 'https://bilibili.com', title: 'Bilibili', description: 'Китайский видеохостинг.', keywords: ['Bilibili', 'Билибили', 'видео'] },
    { url: 'https://twitch.tv', title: 'Twitch', description: 'Платформа для стриминга.', keywords: ['Twitch', 'Твич', 'стриминг'] },
    { url: 'https://vk.com', title: 'ВКонтакте', description: 'Очередная государственная контора, которая ничего из себя не представляет.', keywords: ['ВКонтакте', 'VK', 'соцсеть'] },
    { url: 'https://news.yahoo.co.jp', title: 'Yahoo News Japan', description: 'Японские новости.', keywords: ['Yahoo News', 'Яху Новости', 'новости'] },
    { url: 'https://xhamster.com', title: 'xHamster', description: 'Платформа для взрослого контента.', keywords: ['xHamster', 'взрослый контент'] },
    { url: 'https://mail.ru', title: 'Mail.ru', description: 'Российский портал и почта.', keywords: ['Mail.ru', 'Майл', 'почта'] },
    { url: 'https://sharepoint.com', title: 'SharePoint', description: 'Платформа для совместной работы.', keywords: ['SharePoint', 'Шэрпоинт', 'работа'] },
    { url: 'https://samsung.com', title: 'Samsung', description: 'Официальный сайт Samsung.', keywords: ['Samsung', 'Самсунг', 'технологии'] },
    { url: 'https://fandom.com', title: 'Fandom', description: 'Вики по играм и поп-культуре.', keywords: ['Fandom', 'Фандом', 'вики'] },
    { url: 'https://globo.com', title: 'Globo', description: 'Бразильский медиапортал.', keywords: ['Globo', 'Глобо', 'новости'] },
    { url: 'https://canva.com', title: 'Canva', description: 'Платформа для дизайна.', keywords: ['Canva', 'Канва', 'дизайн'] },
    { url: 'https://xnxx.com', title: 'XNXX', description: 'Платформа для взрослого контента.', keywords: ['XNXX', 'взрослый контент'] },
    { url: 'https://duckduckgo.com', title: 'DuckDuckGo', description: 'Конфиденциальная поисковая система.', keywords: ['DuckDuckGo', 'ДакДакГо', 'поиск'] },
    { url: 'https://aliexpress.com', title: 'AliExpress', description: 'Онлайн-магазин.', keywords: ['AliExpress', 'АлиЭкспресс', 'магазин'] },
    { url: 'https://t.me', title: 'Telegram', description: 'Мессенджер с каналами.', keywords: ['Telegram', 'Телеграм', 'мессенджер'] },
    { url: 'https://pari-match-in.com', title: 'Parimatch', description: 'Платформа для ставок.', keywords: ['Parimatch', 'Париматч', 'ставки'] },
    { url: 'https://weather.com', title: 'Weather', description: 'Прогноз погоды.', keywords: ['Weather', 'Погода', 'прогноз'] },
    { url: 'https://quora.com', title: 'Quora', description: 'Платформа для вопросов и ответов.', keywords: ['Quora', 'Квора', 'вопросы'] },
    { url: 'https://temu.com', title: 'Temu', description: 'Онлайн-магазин.', keywords: ['Temu', 'Тему', 'магазин'] },
    { url: 'https://zoom.us', title: 'Zoom', description: 'Платформа для видеоконференций.', keywords: ['Zoom', 'Зум', 'видео'] },
    { url: 'https://stripchat.com', title: 'Stripchat', description: 'Платформа для взрослого контента.', keywords: ['Stripchat', 'взрослый контент'] },
    { url: 'https://ebay.com', title: 'eBay', description: 'Онлайн-аукцион и магазин.', keywords: ['eBay', 'Ибэй', 'магазин'] },
    { url: 'https://deepseek.com', title: 'DeepSeek', description: 'AI-платформа для исследований.', keywords: ['DeepSeek', 'ИИ', 'AI'] },
    { url: 'https://spotify.com', title: 'Spotify', description: 'Музыкальный стриминговый сервис.', keywords: ['Spotify', 'Спотифай', 'музыка'] },
    { url: 'https://apple.com', title: 'Apple', description: 'Официальный сайт Apple.', keywords: ['Apple', 'Эппл', 'технологии'] },
    { url: 'https://twitter.com', title: 'Twitter', description: 'Социальная сеть для твитов.', keywords: ['Twitter', 'Твиттер', 'соцсеть'] },
    { url: 'https://github.com', title: 'GitHub', description: 'Платформа для разработки и кода.', keywords: ['GitHub', 'Гитхаб', 'код'] },
    { url: 'https://medium.com', title: 'Medium', description: 'Платформа для блогов и статей.', keywords: ['Medium', 'Медиум', 'блог'] },
    { url: 'https://dropbox.com', title: 'Dropbox', description: 'Облачное хранилище файлов.', keywords: ['Dropbox', 'Дропбокс', 'облако'] },
    { url: 'https://trello.com', title: 'Trello', description: 'Инструмент для управления проектами.', keywords: ['Trello', 'Трелло', 'проекты'] },
    { url: 'https://etsy.com', title: 'Etsy', description: 'Маркетплейс для handmade товаров.', keywords: ['Etsy', 'Этси', 'магазин'] },
    { url: 'https://nytimes.com', title: 'The New York Times', description: 'Международные новости.', keywords: ['New York Times', 'NYT', 'новости'] },
    { url: 'https://adobe.com', title: 'Adobe', description: 'Программы для дизайна и творчества.', keywords: ['Adobe', 'Адоб', 'дизайн'] },
    { url: 'https://nvidia.com', title: 'NVIDIA', description: 'Технологии для графики и AI.', keywords: ['NVIDIA', 'Нвидиа', 'технологии'] },
    { url: 'https://paypal.com', title: 'PayPal', description: 'Платёжная система.', keywords: ['PayPal', 'ПейПал', 'платежи'] },
    { url: 'https://shopify.com', title: 'Shopify', description: 'Платформа для интернет-магазинов.', keywords: ['Shopify', 'Шопифай', 'магазин'] },
    { url: 'https://coursera.org', title: 'Coursera', description: 'Онлайн-курсы и обучение.', keywords: ['Coursera', 'Курсера', 'обучение'] },
    { url: 'https://udemy.com', title: 'Udemy', description: 'Платформа для онлайн-курсов.', keywords: ['Udemy', 'Удеми', 'курсы'] },
    { url: 'https://airbnb.com', title: 'Airbnb', description: 'Аренда жилья и путешествия.', keywords: ['Airbnb', 'Эйрбиэнби', 'путешествия'] },
    { url: 'https://uber.com', title: 'Uber', description: 'Сервис такси и доставки.', keywords: ['Uber', 'Убер', 'такси'] },
    { url: 'https://zoho.com', title: 'Zoho', description: 'Бизнес-приложения и CRM.', keywords: ['Zoho', 'Зохо', 'бизнес'] },
    { url: 'https://salesforce.com', title: 'Salesforce', description: 'CRM и облачные решения.', keywords: ['Salesforce', 'Сейлсфорс', 'CRM'] },
    { url: 'https://hulu.com', title: 'Hulu', description: 'Стриминговый сервис для сериалов.', keywords: ['Hulu', 'Хулу', 'сериалы'] },
    { url: 'https://vimeo.com', title: 'Vimeo', description: 'Видеохостинг для профессионалов.', keywords: ['Vimeo', 'Вимео', 'видео'] },
    { url: 'https://dribbble.com', title: 'Dribbble', description: 'Сообщество дизайнеров.', keywords: ['Dribbble', 'Дрибббл', 'дизайн'] },
    { url: 'https://behance.net', title: 'Behance', description: 'Портфолио для креативщиков.', keywords: ['Behance', 'Беханс', 'дизайн'] },
    { url: 'https://patreon.com', title: 'Patreon', description: 'Поддержка авторов контента.', keywords: ['Patreon', 'Патреон', 'креаторы'] },
    { url: 'https://kickstarter.com', title: 'Kickstarter', description: 'Краудфандинг для проектов.', keywords: ['Kickstarter', 'Кикстартер', 'проекты'] },
    { url: 'https://walmart.com', title: 'Walmart', description: 'Сеть магазинов и онлайн-продажи.', keywords: ['Walmart', 'Валмарт', 'магазин'] },
    { url: 'https://target.com', title: 'Target', description: 'Розничная сеть и онлайн-магазин.', keywords: ['Target', 'Таргет', 'магазин'] },
    { url: 'https://booking.com', title: 'Booking', description: 'Бронирование отелей и жилья.', keywords: ['Booking', 'Букинг', 'путешествия'] },
    { url: 'https://expedia.com', title: 'Expedia', description: 'Путешествия и бронирование.', keywords: ['Expedia', 'Экспедия', 'путешествия'] },
    { url: 'https://tripadvisor.com', title: 'TripAdvisor', description: 'Отзывы и советы для путешествий.', keywords: ['TripAdvisor', 'ТрипАдвизор', 'путешествия'] },
    { url: 'https://soundcloud.com', title: 'SoundCloud', description: 'Музыкальная платформа.', keywords: ['SoundCloud', 'Саундклауд', 'музыка'] },
    { url: 'https://bandcamp.com', title: 'Bandcamp', description: 'Музыка и мерч от артистов.', keywords: ['Bandcamp', 'Бэндкамп', 'музыка'] },
    { url: 'https://webflow.com', title: 'Webflow', description: 'Конструктор сайтов без кода.', keywords: ['Webflow', 'Вебфлоу', 'сайты'] },
    { url: 'https://atlassian.com', title: 'Atlassian', description: 'Инструменты для разработки и управления.', keywords: ['Atlassian', 'Атлассиан', 'проекты'] },
    { url: 'https://zendesk.com', title: 'Zendesk', description: 'Платформа для поддержки клиентов.', keywords: ['Zendesk', 'Зендеск', 'поддержка'] },
    { url: 'https://evernote.com', title: 'Evernote', description: 'Заметки и организация.', keywords: ['Evernote', 'Эверноут', 'заметки'] },
    { url: 'https://robinhood.com', title: 'Robinhood', description: 'Платформа для инвестиций.', keywords: ['Robinhood', 'Робингуд', 'инвестиции'] },
    { url: 'https://binance.com', title: 'Binance', description: 'Криптовалютная биржа.', keywords: ['Binance', 'Бинанс', 'крипто'] },
    { url: 'https://coinmarketcap.com', title: 'CoinMarketCap', description: 'Курсы криптовалют.', keywords: ['CoinMarketCap', 'КоинМаркетКап', 'крипто'] },
    { url: 'https://tumblr.com', title: 'Tumblr', description: 'Платформа для блогов и микропостов.', keywords: ['Tumblr', 'Тумблр', 'блог', 'соцсеть'] },
    { url: 'https://mastodon.social', title: 'Mastodon', description: 'Децентрализованная социальная сеть.', keywords: ['Mastodon', 'Мастердон', 'соцсеть', 'децентрализация'] },
    { url: 'https://gab.com', title: 'Gab', description: 'Социальная сеть с акцентом на свободу слова.', keywords: ['Gab', 'Габ', 'соцсеть', 'свобода слова'] },
    { url: 'https://parler.com', title: 'Parler', description: 'Платформа для общения и новостей.', keywords: ['Parler', 'Парлер', 'соцсеть', 'новости'] },
    { url: 'https://gettr.com', title: 'Gettr', description: 'Социальная сеть для обмена мнениями.', keywords: ['Gettr', 'Геттр', 'соцсеть', 'дискуссии'] },
    { url: 'https://line.me', title: 'Line', description: 'Японский мессенджер и соцсеть.', keywords: ['Line', 'Лайн', 'мессенджер', 'Япония'] },
    { url: 'https://kakao.com', title: 'Kakao', description: 'Южнокорейский мессенджер и сервисы.', keywords: ['Kakao', 'Какао', 'мессенджер', 'Корея'] },
    { url: 'https://weixin.qq.com', title: 'WeChat', description: 'Китайский мессенджер и суперприложение.', keywords: ['WeChat', 'ВиЧат', 'мессенджер', 'Китай'] },
    { url: 'https://matrix.org', title: 'Matrix', description: 'Открытый протокол для чатов.', keywords: ['Matrix', 'Матрикс', 'мессенджер', 'приватность'] },
    { url: 'https://zulily.com', title: 'Zulily', description: 'Онлайн-магазин одежды и товаров.', keywords: ['Zulily', 'Зулили', 'магазин', 'одежда'] },
    { url: 'https://overstock.com', title: 'Overstock', description: 'Магазин мебели и товаров для дома.', keywords: ['Overstock', 'Оверсток', 'мебель', 'дом'] },
    { url: 'https://wayfair.com', title: 'Wayfair', description: 'Онлайн-магазин мебели и декора.', keywords: ['Wayfair', 'Вейфер', 'мебель', 'декор'] },
    { url: 'https://newegg.com', title: 'Newegg', description: 'Магазин электроники и комплектующих.', keywords: ['Newegg', 'Ньюэгг', 'электроника', 'компьютеры'] },
    { url: 'https://costco.com', title: 'Costco', description: 'Сеть оптовых магазинов.', keywords: ['Costco', 'Костко', 'магазин', 'опт'] },
    { url: 'https://kohls.com', title: "Kohl's", description: 'Магазин одежды и товаров для дома.', keywords: ["Kohl's", 'Колс', 'одежда', 'дом'] },
    { url: 'https://macys.com', title: "Macy's", description: 'Универмаг с одеждой и аксессуарами.', keywords: ["Macy's", 'Мейсис', 'одежда', 'магазин'] },
    { url: 'https://nordstrom.com', title: 'Nordstrom', description: 'Магазин модной одежды и обуви.', keywords: ['Nordstrom', 'Нордстром', 'мода', 'одежда'] },
    { url: 'https://zara.com', title: 'Zara', description: 'Бренд модной одежды.', keywords: ['Zara', 'Зара', 'мода', 'одежда'] },
    { url: 'https://hm.com', title: 'H&M', description: 'Магазин доступной модной одежды.', keywords: ['H&M', 'Эйч энд Эм', 'мода', 'одежда'] },
    { url: 'https://uniqlo.com', title: 'Uniqlo', description: 'Японский бренд повседневной одежды.', keywords: ['Uniqlo', 'Юникло', 'одежда', 'Япония'] },
    { url: 'https://gap.com', title: 'Gap', description: 'Американский бренд одежды.', keywords: ['Gap', 'Гэп', 'одежда', 'мода'] },
    { url: 'https://forever21.com', title: 'Forever 21', description: 'Магазин молодежной моды.', keywords: ['Forever 21', 'Форевер 21', 'мода', 'одежда'] },
    { url: 'https://shein.com', title: 'Shein', description: 'Онлайн-магазин бюджетной одежды.', keywords: ['Shein', 'Шейн', 'одежда', 'мода'] },
    { url: 'https://asos.com', title: 'ASOS', description: 'Онлайн-магазин модной одежды.', keywords: ['ASOS', 'Асос', 'мода', 'одежда'] },
    { url: 'https://boohoo.com', title: 'Boohoo', description: 'Магазин трендовой молодежной одежды.', keywords: ['Boohoo', 'Буху', 'мода', 'одежда'] },
    { url: 'https://reiss.com', title: 'Reiss', description: 'Бренд премиальной одежды.', keywords: ['Reiss', 'Рейсс', 'мода', 'одежда'] },
    { url: 'https://ted.com', title: 'TED', description: 'Платформа для вдохновляющих лекций.', keywords: ['TED', 'ТЭД', 'лекции', 'образование'] },
    { url: 'https://masterclass.com', title: 'MasterClass', description: 'Онлайн-курсы от экспертов.', keywords: ['MasterClass', 'МастерКласс', 'курсы', 'обучение'] },
    { url: 'https://skillshare.com', title: 'Skillshare', description: 'Платформа для творческих курсов.', keywords: ['Skillshare', 'Скиллшер', 'курсы', 'творчество'] },
    { url: 'https://pluralsight.com', title: 'Pluralsight', description: 'Курсы по IT и технологиям.', keywords: ['Pluralsight', 'Плуралсайт', 'IT', 'обучение'] },
    { url: 'https://linkedin.com/learning', title: 'LinkedIn Learning', description: 'Курсы для профессионального роста.', keywords: ['LinkedIn Learning', 'Линкедин', 'курсы', 'работа'] },
    { url: 'https://futurelearn.com', title: 'FutureLearn', description: 'Онлайн-курсы от университетов.', keywords: ['FutureLearn', 'ФьючерЛерн', 'курсы', 'обучение'] },
    { url: 'https://open.edu', title: 'Open University', description: 'Бесплатные образовательные ресурсы.', keywords: ['Open University', 'Оупен Юниверсити', 'обучение', 'курсы'] },
    { url: 'https://alison.com', title: 'Alison', description: 'Бесплатные онлайн-курсы.', keywords: ['Alison', 'Алисон', 'курсы', 'обучение'] },
    { url: 'https://udacity.com', title: 'Udacity', description: 'Курсы по технологиям и программированию.', keywords: ['Udacity', 'Юдасити', 'программирование', 'курсы'] },
    { url: 'https://gog.com', title: 'GOG', description: 'Магазин цифровых игр без DRM.', keywords: ['GOG', 'Гог', 'игры', 'магазин'] },
    { url: 'https://itch.io', title: 'Itch.io', description: 'Платформа для инди-игр.', keywords: ['Itch.io', 'Итч', 'игры', 'инди'] },
    { url: 'https://humblebundle.com', title: 'Humble Bundle', description: 'Магазин игр с благотворительностью.', keywords: ['Humble Bundle', 'Хамбл Бандл', 'игры', 'магазин'] },
    { url: 'https://gamejolt.com', title: 'Game Jolt', description: 'Сообщество для инди-игр.', keywords: ['Game Jolt', 'Гейм Джолт', 'игры', 'инди'] },
    { url: 'https://kongregate.com', title: 'Kongregate', description: 'Платформа для браузерных игр.', keywords: ['Kongregate', 'Конгрегейт', 'игры', 'браузер'] },
    { url: 'https://miniclip.com', title: 'Miniclip', description: 'Браузерные и мобильные игры.', keywords: ['Miniclip', 'Миниклип', 'игры', 'браузер'] },
    { url: 'https://newgrounds.com', title: 'Newgrounds', description: 'Платформа для игр и анимации.', keywords: ['Newgrounds', 'Ньюграундс', 'игры', 'анимация'] },
    { url: 'https://armorgames.com', title: 'Armor Games', description: 'Браузерные игры и сообщество.', keywords: ['Armor Games', 'Армор Геймс', 'игры', 'браузер'] },
    { url: 'https://crazygames.com', title: 'Crazy Games', description: 'Коллекция бесплатных браузерных игр.', keywords: ['Crazy Games', 'Крейзи Геймс', 'игры', 'браузер'] },
    { url: 'https://addictinggames.com', title: 'Addicting Games', description: 'Платформа для браузерных игр.', keywords: ['Addicting Games', 'Аддиктинг Геймс', 'игры', 'браузер'] },
    { url: 'https://espn.com', title: 'ESPN', description: 'Спортивные новости и трансляции.', keywords: ['ESPN', 'ЕСПН', 'спорт', 'новости'] },
    { url: 'https://bleacherreport.com', title: 'Bleacher Report', description: 'Спортивные новости и аналитика.', keywords: ['Bleacher Report', 'Бличер Репорт', 'спорт', 'новости'] },
    { url: 'https://cbssports.com', title: 'CBS Sports', description: 'Спортивные новости и результаты.', keywords: ['CBS Sports', 'СиБиЭс Спортс', 'спорт', 'новости'] },
    { url: 'https://si.com', title: 'Sports Illustrated', description: 'Журнал и сайт о спорте.', keywords: ['Sports Illustrated', 'Спортс Иллюстрейтед', 'спорт', 'новости'] },
    { url: 'https://foxsports.com', title: 'Fox Sports', description: 'Спортивные новости и трансляции.', keywords: ['Fox Sports', 'Фокс Спортс', 'спорт', 'новости'] },
    { url: 'https://nbcsports.com', title: 'NBC Sports', description: 'Спортивные трансляции и новости.', keywords: ['NBC Sports', 'ЭнБиСи Спортс', 'спорт', 'новости'] },
    { url: 'https://eurosport.com', title: 'Eurosport', description: 'Европейские спортивные новости.', keywords: ['Eurosport', 'Евроспорт', 'спорт', 'новости'] },
    { url: 'https://thesun.co.uk', title: 'The Sun', description: 'Британская газета с новостями.', keywords: ['The Sun', 'Сан', 'новости', 'медиа'] },
    { url: 'https://dailymail.co.uk', title: 'Daily Mail', description: 'Британская газета и новости.', keywords: ['Daily Mail', 'Дейли Мейл', 'новости', 'медиа'] },
    { url: 'https://telegraph.co.uk', title: 'The Telegraph', description: 'Британская газета с новостями.', keywords: ['The Telegraph', 'Телеграф', 'новости', 'медиа'] },
    { url: 'https://independent.co.uk', title: 'The Independent', description: 'Британские и мировые новости.', keywords: ['The Independent', 'Индепендент', 'новости', 'медиa'] },
    { url: 'https://aljazeera.com', title: 'Al Jazeera', description: 'Международные новости из Катара.', keywords: ['Al Jazeera', 'Аль Джазира', 'новости', 'медиа'] },
    { url: 'https://rt.com', title: 'RT', description: 'Российский новостной канал.', keywords: ['RT', 'Ар Ти', 'новости', 'медиа'] },
    { url: 'https://apnews.com', title: 'Associated Press', description: 'Международное новостное агентство.', keywords: ['Associated Press', 'АП', 'новости', 'медиа'] },
    { url: 'https://npr.org', title: 'NPR', description: 'Национальное общественное радио США.', keywords: ['NPR', 'Эн Пи Ар', 'новости', 'радио'] },
    { url: 'https://pbs.org', title: 'PBS', description: 'Общественное телевидение США.', keywords: ['PBS', 'Пи Би Эс', 'новости', 'медиа'] },
    { url: 'https://time.com', title: 'Time', description: 'Американский новостной журнал.', keywords: ['Time', 'Тайм', 'новости', 'журнал'] },
    { url: 'https://newsweek.com', title: 'Newsweek', description: 'Международный новостной журнал.', keywords: ['Newsweek', 'Ньюсвик', 'новости', 'журнал'] },
    { url: 'https://economist.com', title: 'The Economist', description: 'Журнал о бизнесе и экономике.', keywords: ['The Economist', 'Экономист', 'новости', 'бизнес'] },
    { url: 'https://politico.com', title: 'Politico', description: 'Новости и аналитика политики.', keywords: ['Politico', 'Политико', 'новости', 'политика'] },
    { url: 'https://axios.com', title: 'Axios', description: 'Новости и аналитика технологий.', keywords: ['Axios', 'Аксиос', 'новости', 'технологии'] },
    { url: 'https://vox.com', title: 'Vox', description: 'Новости и объяснения текущих событий.', keywords: ['Vox', 'Вокс', 'новости', 'медиа'] },
    { url: 'https://slate.com', title: 'Slate', description: 'Онлайн-журнал о культуре и политике.', keywords: ['Slate', 'Слейт', 'новости', 'культура'] },
    { url: 'https://buzzfeed.com', title: 'BuzzFeed', description: 'Новости, тесты и развлекательный контент.', keywords: ['BuzzFeed', 'БаззФид', 'новости', 'развлечения'] },
    { url: 'https://huffpost.com', title: 'HuffPost', description: 'Новости и лайфстайл контент.', keywords: ['HuffPost', 'ХаффПост', 'новости', 'лайфстайл'] },
    { url: 'https://vice.com', title: 'Vice', description: 'Журнал о культуре и новостях.', keywords: ['Vice', 'Вайс', 'новости', 'культура'] },
    { url: 'https://truthsocial.com', title: 'Truth Social', description: 'Социальная сеть для обмена мнениями.', keywords: ['Truth Social', 'Трут Социал', 'соцсеть', 'новости'] },
    { url: 'https://rumble.com', title: 'Rumble', description: 'Платформа для видео и стриминга.', keywords: ['Rumble', 'Рамбл', 'видео', 'стриминг'] },
    { url: 'https://locals.com', title: 'Locals', description: 'Сообщество для авторов контента.', keywords: ['Locals', 'Локалс', 'соцсеть', 'креаторы'] },
    { url: 'https://mewe.com', title: 'MeWe', description: 'Социальная сеть с акцентом на приватность.', keywords: ['MeWe', 'МиВи', 'соцсеть', 'приватность'] },
    { url: 'https://nextdoor.com', title: 'Nextdoor', description: 'Социальная сеть для соседских сообществ.', keywords: ['Nextdoor', 'Некстдор', 'соцсеть', 'соседи'] },
    { url: 'https://session.com', title: 'Session', description: 'Мессенджер с фокусом на конфиденциальность.', keywords: ['Session', 'Сессион', 'мессенджер', 'приватность'] },
    { url: 'https://wire.com', title: 'Wire', description: 'Шифрованный мессенджер для бизнеса.', keywords: ['Wire', 'Вайр', 'мессенджер', 'безопасность'] },
    { url: 'https://threema.ch', title: 'Threema', description: 'Швейцарский мессенджер с высокой приватностью.', keywords: ['Threema', 'Трима', 'мессенджер', 'приватность'] },
    { url: 'https://qvc.com', title: 'QVC', description: 'Онлайн-магазин товаров для дома и моды.', keywords: ['QVC', 'Кью Ви Си', 'магазин', 'мода'] },
    { url: 'https://hsn.com', title: 'HSN', description: 'Магазин товаров для дома и электроники.', keywords: ['HSN', 'Эйч Эс Эн', 'магазин', 'дом'] },
    { url: 'https://bedbathandbeyond.com', title: 'Bed Bath & Beyond', description: 'Магазин товаров для дома.', keywords: ['Bed Bath & Beyond', 'Бед Бат', 'дом', 'магазин'] },
    { url: 'https://crateandbarrel.com', title: 'Crate & Barrel', description: 'Мебель и декор для дома.', keywords: ['Crate & Barrel', 'Крейт энд Баррел', 'мебель', 'декор'] },
    { url: 'https://westelm.com', title: 'West Elm', description: 'Магазин современной мебели и декора.', keywords: ['West Elm', 'Вест Элм', 'мебель', 'декор'] },
    { url: 'https://potterybarn.com', title: 'Pottery Barn', description: 'Магазин мебели и товаров для дома.', keywords: ['Pottery Barn', 'Поттери Барн', 'мебель', 'дом'] },
    { url: 'https://anthropologie.com', title: 'Anthropologie', description: 'Магазин одежды и декора в стиле бохо.', keywords: ['Anthropologie', 'Антрополоджи', 'мода', 'декор'] },
    { url: 'https://urbanoutfitters.com', title: 'Urban Outfitters', description: 'Магазин молодежной одежды и аксессуаров.', keywords: ['Urban Outfitters', 'Урбан Аутфиттерс', 'мода', 'одежда'] },
    { url: 'https://freepeople.com', title: 'Free People', description: 'Бренд одежды в стиле бохо.', keywords: ['Free People', 'Фри Пипл', 'мода', 'одежда'] },
    { url: 'https://madewell.com', title: 'Madewell', description: 'Магазин повседневной женской одежды.', keywords: ['Madewell', 'Мейдвелл', 'одежда', 'мода'] },
    { url: 'https://bonobos.com', title: 'Bonobos', description: 'Магазин мужской одежды.', keywords: ['Bonobos', 'Бонобос', 'одежда', 'мода'] },
    { url: 'https://everlane.com', title: 'Everlane', description: 'Бренд экологичной одежды.', keywords: ['Everlane', 'Эверлейн', 'одежда', 'эко'] },
    { url: 'https://reformation.com', title: 'Reformation', description: 'Экологичная модная одежда.', keywords: ['Reformation', 'Реформация', 'мода', 'эко'] },
    { url: 'https://allbirds.com', title: 'Allbirds', description: 'Экологичная обувь и одежда.', keywords: ['Allbirds', 'Олбердс', 'обувь', 'эко'] },
    { url: 'https://rothy.com', title: 'Rothy', description: 'Экологичная обувь из переработанных материалов.', keywords: ['Rothy', 'Роти', 'обувь', 'эко'] },
    { url: 'https://toms.com', title: 'TOMS', description: 'Обувь и аксессуары с социальной миссией.', keywords: ['TOMS', 'Томс', 'обувь', 'мода'] },
    { url: 'https://skims.com', title: 'SKIMS', description: 'Бренд нижнего белья и одежды.', keywords: ['SKIMS', 'Скимс', 'одежда', 'белье'] },
    { url: 'https://openstreetmap.org', title: 'OpenStreetMap', description: 'Открытая карта мира.', keywords: ['OpenStreetMap', 'ОупенСтритМап', 'карты', 'навигация'] },
    { url: 'https://waze.com', title: 'Waze', description: 'Навигатор с данными от сообщества.', keywords: ['Waze', 'Вейз', 'навигация', 'карты'] },
    { url: 'https://mapquest.com', title: 'MapQuest', description: 'Сервис карт и маршрутов.', keywords: ['MapQuest', 'МапКвест', 'карты', 'навигация'] },
    { url: 'https://here.com', title: 'HERE', description: 'Платформа для карт и геолокации.', keywords: ['HERE', 'Хир', 'карты', 'геолокация'] },
    { url: 'https://tomtom.com', title: 'TomTom', description: 'Сервис навигации и карт.', keywords: ['TomTom', 'ТомТом', 'навигация', 'карты'] },
    { url: 'https://strava.com', title: 'Strava', description: 'Приложение для отслеживания спорта.', keywords: ['Strava', 'Страва', 'спорт', 'фитнес'] },
    { url: 'https://fitbit.com', title: 'Fitbit', description: 'Устройства и приложение для фитнеса.', keywords: ['Fitbit', 'Фитбит', 'фитнес', 'здоровье'] },
    { url: 'https://myfitnesspal.com', title: 'MyFitnessPal', description: 'Приложение для учета питания.', keywords: ['MyFitnessPal', 'МайФитнесПал', 'питание', 'здоровье'] },
    { url: 'https://peloton.com', title: 'Peloton', description: 'Фитнес-оборудование и тренировки.', keywords: ['Peloton', 'Пелотон', 'фитнес', 'тренировки'] },
    { url: 'https://zwift.com', title: 'Zwift', description: 'Платформа для виртуального велоспорта.', keywords: ['Zwift', 'Звифт', 'спорт', 'велоспорт'] },
    { url: 'https://komoot.com', title: 'Komoot', description: 'Приложение для планирования маршрутов.', keywords: ['Komoot', 'Комут', 'спорт', 'маршруты'] },
    { url: 'https://alltrails.com', title: 'AllTrails', description: 'Приложение для пеших маршрутов.', keywords: ['AllTrails', 'ОлТрейлс', 'туризм', 'маршруты'] },
    { url: 'https://gaia.com', title: 'Gaia', description: 'Платформа для йоги и медитации.', keywords: ['Gaia', 'Гайя', 'йога', 'медитация'] },
    { url: 'https://calm.com', title: 'Calm', description: 'Приложение для медитации и сна.', keywords: ['Calm', 'Калм', 'медитация', 'сон'] },
    { url: 'https://headspace.com', title: 'Headspace', description: 'Приложение для медитации и осознанности.', keywords: ['Headspace', 'Хедспейс', 'медитация', 'здоровье'] },
    { url: 'https://webmd.com', title: 'WebMD', description: 'Информация о здоровье и медицине.', keywords: ['WebMD', 'ВебЭмДи', 'здоровье', 'медицина'] },
    { url: 'https://mayoclinic.org', title: 'Mayo Clinic', description: 'Медицинские статьи и советы.', keywords: ['Mayo Clinic', 'Майо Клиник', 'здоровье', 'медицина'] },
    { url: 'https://healthline.com', title: 'Healthline', description: 'Ресурс о здоровье и благополучии.', keywords: ['Healthline', 'Хелслайн', 'здоровье', 'медицина'] },
    { url: 'https://medscape.com', title: 'Medscape', description: 'Медицинские новости и образование.', keywords: ['Medscape', 'Медскейп', 'медицина', 'новости'] },
    { url: 'https://drugs.com', title: 'Drugs.com', description: 'Информация о лекарствах.', keywords: ['Drugs.com', 'Драгс', 'медицина', 'лекарства'] },
    { url: 'https://kayak.com', title: 'Kayak', description: 'Поиск авиабилетов и отелей.', keywords: ['Kayak', 'Каяк', 'путешествия', 'бронирование'] },
    { url: 'https://skyscanner.com', title: 'Skyscanner', description: 'Сравнение цен на авиабилетов.', keywords: ['Skyscanner', 'Скайсканнер', 'путешествия', 'авиабилеты'] },
    { url: 'https://momondo.com', title: 'Momondo', description: 'Поиск дешевых авиабилетов.', keywords: ['Momondo', 'Момондо', 'путешествия', 'авиабилеты'] },
    { url: 'https://trivago.com', title: 'Trivago', description: 'Сравнение цен на отели.', keywords: ['Trivago', 'Триваго', 'путешествия', 'отели'] },
    { url: 'https://hotels.com', title: 'Hotels.com', description: 'Бронирование отелей по всему миру.', keywords: ['Hotels.com', 'Хотелс', 'путешествия', 'отели'] },
    { url: 'https://agoda.com', title: 'Agoda', description: 'Платформа для бронирования жилья.', keywords: ['Agoda', 'Агода', 'путешествия', 'отели'] },
    { url: 'https://vrbo.com', title: 'Vrbo', description: 'Аренда домов для отдыха.', keywords: ['Vrbo', 'Врбо', 'путешествия', 'жилье'] },
    { url: 'https://lonelyplanet.com', title: 'Lonely Planet', description: 'Путеводители и советы для путешествий.', keywords: ['Lonely Planet', 'Лонели Планет', 'путешествия', 'гид'] },
    { url: 'https://roughguides.com', title: 'Rough Guides', description: 'Путеводители для путешественников.', keywords: ['Rough Guides', 'Раф Гайдс', 'путешествия', 'гид'] },
    { url: 'https://fodors.com', title: "Fodor's", description: 'Советы и гиды для путешествий.', keywords: ["Fodor's", 'Фодорс', 'путешествия', 'гид'] },
    { url: 'https://trip.com', title: 'Trip.com', description: 'Бронирование путешествий и отелей.', keywords: ['Trip.com', 'Трип', 'путешествия', 'бронирование'] },
    { url: 'https://viator.com', title: 'Viator', description: 'Бронирование экскурсий и туров.', keywords: ['Viator', 'Виатор', 'путешествия', 'туры'] },
    { url: 'https://getyourguide.com', title: 'GetYourGuide', description: 'Экскурсии и активности для туристов.', keywords: ['GetYourGuide', 'ГетЮрГайд', 'путешествия', 'туры'] },
    { url: 'https://klook.com', title: 'Klook', description: 'Бронирование активностей и билетов.', keywords: ['Klook', 'Клук', 'путешествия', 'активности'] },
    { url: 'https://brainly.com', title: 'Brainly', description: 'Платформа для помощи с учебой.', keywords: ['Brainly', 'Брейнли', 'образование', 'учеба'] },
    { url: 'https://chegg.com', title: 'Chegg', description: 'Ресурсы для студентов и учебников.', keywords: ['Chegg', 'Чегг', 'образование', 'учебники'] },
    { url: 'https://quizlet.com', title: 'Quizlet', description: 'Инструмент для учебы и карточек.', keywords: ['Quizlet', 'Квизлет', 'образование', 'учеба'] },
    { url: 'https://duolingo.com', title: 'Duolingo', description: 'Приложение для изучения языков.', keywords: ['Duolingo', 'Дуолинго', 'языки', 'обучение'] },
    { url: 'https://busuu.com', title: 'Busuu', description: 'Платформа для изучения языков.', keywords: ['Busuu', 'Бусу', 'языки', 'обучение'] },
    { url: 'https://babbel.com', title: 'Babbel', description: 'Курсы для изучения языков.', keywords: ['Babbel', 'Баббель', 'языки', 'обучение'] },
    { url: 'https://rosettastone.com', title: 'Rosetta Stone', description: 'Программа для изучения языков.', keywords: ['Rosetta Stone', 'Розетта Стоун', 'языки', 'обучение'] },
    { url: 'https://memrise.com', title: 'Memrise', description: 'Приложение для запоминания и языков.', keywords: ['Memrise', 'Мемрайз', 'языки', 'обучение'] },
    { url: 'https://thepiratebay.org', title: 'The Pirate Bay', description: 'Популярный торрент-трекер для файлов.', keywords: ['The Pirate Bay', 'Пират Бэй', 'торрент', 'скачивание'] },
    { url: 'https://1337x.to', title: '1337x', description: 'Торрент-сайт с играми и софтом.', keywords: ['1337x', 'Литс', 'торрент', 'игры'] },
    { url: 'https://torrentz2.nz', title: 'Torrentz2', description: 'Поисковик торрентов по множеству сайтов.', keywords: ['Torrentz2', 'Торрентз', 'торрент', 'поиск'] },
    { url: 'https://rarbg.to', title: 'RARBG', description: 'Торрент-трекер с фильмами и играми.', keywords: ['RARBG', 'Рарбг', 'торрент', 'софт'] },
    { url: 'https://yts.mx', title: 'YTS', description: 'Торрент-сайт для фильмов в высоком качестве.', keywords: ['YTS', 'Вай Ти Эс', 'торрент', 'фильмы'] },
    { url: 'https://eztv.re', title: 'EZTV', description: 'Торрент-сайт для сериалов.', keywords: ['EZTV', 'Изи ТВ', 'торрент', 'сериалы'] },
    { url: 'https://torrentdownloads.pro', title: 'TorrentDownloads', description: 'Торрент-трекер для софта и игр.', keywords: ['TorrentDownloads', 'Торрент Даунлодс', 'торрент', 'софт'] },
    { url: 'https://limetorrents.lol', title: 'LimeTorrents', description: 'Торрент-сайт с приложениями и медиа.', keywords: ['LimeTorrents', 'Лайм Торрентс', 'торрент', 'медиа'] },
    { url: 'https://torrentgalaxy.to', title: 'TorrentGalaxy', description: 'Торрент-трекер с разнообразным контентом.', keywords: ['TorrentGalaxy', 'Торрент Гэлакси', 'торрент', 'файлы'] },
    { url: 'https://nyaa.si', title: 'Nyaa', description: 'Торрент-сайт для аниме и манги.', keywords: ['Nyaa', 'Няя', 'торрент', 'аниме'] },
    { url: 'https://mac-torrents.io', title: 'Mac Torrents', description: 'Торренты для macOS приложений.', keywords: ['Mac Torrents', 'Мак Торрентс', 'торрент', 'macOS'] },
    { url: 'https://nmac.to', title: 'Nmac', description: 'Сайт с приложениями для Mac.', keywords: ['Nmac', 'Нмак', 'софт', 'macOS'] },
    { url: 'https://haxmac.cc', title: 'Haxmac', description: 'Ресурс для macOS софта и игр.', keywords: ['Haxmac', 'Хаксмак', 'софт', 'macOS'] },
    { url: 'https://oceanofmac.net', title: 'Ocean of Mac', description: 'Платформа с macOS приложениями.', keywords: ['Ocean of Mac', 'Оушен оф Мак', 'софт', 'macOS'] },
    { url: 'https://macbed.com', title: 'MacBed', description: 'Сайт для скачивания macOS софта.', keywords: ['MacBed', 'МакБед', 'софт', 'macOS'] },
    { url: 'https://xclient.info', title: 'XClient', description: 'Ресурс с приложениями для Mac.', keywords: ['XClient', 'ИксКлиент', 'софт', 'macOS'] },
    { url: 'https://filecr.com', title: 'FileCR', description: 'Платформа для скачивания софта.', keywords: ['FileCR', 'ФайлСиАр', 'софт', 'торрент'] },
    { url: 'https://cracked.io', title: 'Cracked.io', description: 'Форум с софтом и инструментами.', keywords: ['Cracked.io', 'Кракед', 'софт', 'форум'] },
    { url: 'https://torrentmac.net', title: 'TorrentMac', description: 'Торренты для macOS софта.', keywords: ['TorrentMac', 'ТоррентМак', 'торрент', 'macOS'] },
    { url: 'https://getintopc.com', title: 'GetIntoPC', description: 'Сайт для скачивания Windows софта.', keywords: ['GetIntoPC', 'ГетИнтуПиСи', 'софт', 'Windows'] },
    { url: 'https://igg-games.com', title: 'IGG Games', description: 'Торренты для компьютерных игр.', keywords: ['IGG Games', 'Ай Джи Джи', 'игры', 'торрент'] },
    { url: 'https://fitgirl-repacks.site', title: 'FitGirl Repacks', description: 'Репаки игр для скачивания.', keywords: ['FitGirl', 'ФитГёрл', 'игры', 'торрент'] },
    { url: 'https://vero.co', title: 'Vero', description: 'Социальная сеть для творчества.', keywords: ['Vero', 'Веро', 'соцсеть', 'творчество'] },
    { url: 'https://ello.co', title: 'Ello', description: 'Сообщество для художников и дизайнеров.', keywords: ['Ello', 'Элло', 'соцсеть', 'арт'] },
    { url: 'https://lulus.com', title: 'Lulus', description: 'Магазин женской модной одежды.', keywords: ['Lulus', 'Лулус', 'мода', 'одежда'] },
    { url: 'https://nastygal.com', title: 'Nasty Gal', description: 'Магазин трендовой женской одежды.', keywords: ['Nasty Gal', 'Насти Гэл', 'мода', 'одежда'] },
    { url: 'https://prettylittlething.com', title: 'PrettyLittleThing', description: 'Магазин молодежной моды.', keywords: ['PrettyLittleThing', 'ПреттиЛитлТинг', 'мода', 'одежда'] },
    { url: 'https://fashionnova.com', title: 'Fashion Nova', description: 'Бренд модной одежды.', keywords: ['Fashion Nova', 'Фэшн Нова', 'мода', 'одежда'] },
    { url: 'https://missguided.com', title: 'Missguided', description: 'Магазин женской одежды.', keywords: ['Missguided', 'Миссгайдед', 'мода', 'одежда'] },
    { url: 'https://sephora.com', title: 'Sephora', description: 'Магазин косметики и парфюмерии.', keywords: ['Sephora', 'Сефора', 'косметика', 'магазин'] },
    { url: 'https://ulta.com', title: 'Ulta Beauty', description: 'Магазин косметики и ухода.', keywords: ['Ulta', 'Улта', 'косметика', 'магазин'] },
    { url: 'https://glossier.com', title: 'Glossier', description: 'Бренд косметики и ухода за кожей.', keywords: ['Glossier', 'Глоссиер', 'косметика', 'уход'] },
    { url: 'https://todoist.com', title: 'Todoist', description: 'Приложение для списка дел.', keywords: ['Todoist', 'Тудуист', 'задачи', 'списки'] },
    { url: 'https://italki.com', title: 'italki', description: 'Платформа для изучения языков с репетиторами.', keywords: ['italki', 'Айтолки', 'языки', 'обучение'] },
    { url: 'https://preply.com', title: 'Preply', description: 'Онлайн-репетиторы для языков.', keywords: ['Preply', 'Препли', 'языки', 'репетиторы'] },
    { url: 'https://lingq.com', title: 'LingQ', description: 'Приложение для изучения языков.', keywords: ['LingQ', 'ЛингКью', 'языки', 'обучение'] },
    { url: 'https://tandem.net', title: 'Tandem', description: 'Обмен языками с носителями.', keywords: ['Tandem', 'Тандем', 'языки', 'обучение'] },
    { url: 'https://edx.org', title: 'edX', description: 'Онлайн-курсы от университетов.', keywords: ['edX', 'ИдиЭкс', 'курсы', 'обучение'] },
    { url: 'https://whoop.com', title: 'WHOOP', description: 'Трекер для фитнеса и здоровья.', keywords: ['WHOOP', 'Вуп', 'фитнес', 'здоровье'] },
    { url: 'https://ouraring.com', title: 'Oura', description: 'Умное кольцо для отслеживания здоровья.', keywords: ['Oura', 'Оура', 'здоровье', 'трекер'] },
    { url: 'https://noom.com', title: 'Noom', description: 'Приложение для похудения и здоровья.', keywords: ['Noom', 'Нум', 'здоровье', 'похудение'] },
    { url: 'https://lifesum.com', title: 'Lifesum', description: 'Приложение для питания и фитнеса.', keywords: ['Lifesum', 'Лайфсам', 'питание', 'фитнес'] },
    { url: 'https://8fit.com', title: '8fit', description: 'Приложение для тренировок и питания.', keywords: ['8fit', 'ЭйтФит', 'фитнес', 'питание'] },
    { url: 'https://hopper.com', title: 'Hopper', description: 'Приложение для поиска авиабилетов.', keywords: ['Hopper', 'Хоппер', 'путешествия', 'авиабилеты'] },
    { url: 'https://rome2rio.com', title: 'Rome2Rio', description: 'Планирование маршрутов путешествий.', keywords: ['Rome2Rio', 'РоумТуРио', 'путешествия', 'маршруты'] },
    { url: 'https://wanderlog.com', title: 'Wanderlog', description: 'Планировщик путешествий и маршрутов.', keywords: ['Wanderlog', 'Вандерлог', 'путешествия', 'план'] },
    { url: 'https://culturetrip.com', title: 'Culture Trip', description: 'Гиды и статьи о путешествиях.', keywords: ['Culture Trip', 'Калчер Трип', 'путешествия', 'гиды'] },
    { url: 'https://roadtrippers.com', title: 'Roadtrippers', description: 'Планировщик автопутешествий.', keywords: ['Roadtrippers', 'Роудтрипперс', 'путешествия', 'авто'] },
    { url: 'https://businessinsider.com', title: 'Business Insider', description: 'Новости технологий и финансов.', keywords: ['Business Insider', 'Бизнес Инсайдер', 'новости', 'технологии'] },
    { url: 'https://techcrunch.com', title: 'TechCrunch', description: 'Новости технологий и стартапов.', keywords: ['TechCrunch', 'ТекКранч', 'технологии', 'новости'] },
    { url: 'https://gamepix.com', title: 'GamePix', description: 'Платформа для браузерных игр.', keywords: ['GamePix', 'ГеймПикс', 'игры', 'браузер'] },
    { url: 'https://poki.com', title: 'Poki', description: 'Бесплатные онлайн-игры.', keywords: ['Poki', 'Поки', 'игры', 'онлайн'] },
    { url: 'https://friv.com', title: 'Friv', description: 'Коллекция браузерных игр.', keywords: ['Friv', 'Фрив', 'игры', 'браузер'] },
    { url: 'https://agamestudio.com', title: 'Agame', description: 'Платформа для онлайн-игр.', keywords: ['Agame', 'ЭйГейм', 'игры', 'онлайн'] },
    { url: 'https://coolmathgames.com', title: 'Coolmath Games', description: 'Образовательные и казуальные игры.', keywords: ['Coolmath Games', 'КулМат', 'игры', 'образование'] },
    { url: 'https://procreate.com', title: 'Procreate', description: 'Приложение для цифрового рисования.', keywords: ['Procreate', 'Прокриейт', 'дизайн', 'арт'] },
    { url: 'https://affinity.serif.com', title: 'Affinity', description: 'Программы для дизайна и фото.', keywords: ['Affinity', 'Аффинити', 'дизайн', 'фото'] },
    { url: 'https://coreldraw.com', title: 'CorelDRAW', description: 'Инструмент для векторного дизайна.', keywords: ['CorelDRAW', 'КорелДро', 'дизайн', 'графика'] },
    { url: 'https://crello.com', title: 'Crello', description: 'Платформа для создания графики.', keywords: ['Crello', 'Крелло', 'дизайн', 'графика'] },
    { url: 'https://vectr.com', title: 'Vectr', description: 'Бесплатный векторный редактор.', keywords: ['Vectr', 'Вектр', 'дизайн', 'графика'] },
    { url: 'https://upwork.com', title: 'Upwork', description: 'Платформа для фриланса.', keywords: ['Upwork', 'Апворк', 'фриланс', 'работа'] },
    { url: 'https://fiverr.com', title: 'Fiverr', description: 'Маркетплейс для фриланс-услуг.', keywords: ['Fiverr', 'Файвер', 'фриланс', 'услуги'] },
    { url: 'https://freelancer.com', title: 'Freelancer', description: 'Платформа для найма фрилансеров.', keywords: ['Freelancer', 'Фрилансер', 'работа', 'услуги'] },
    { url: 'https://taskrabbit.com', title: 'TaskRabbit', description: 'Сервис для бытовых задач.', keywords: ['TaskRabbit', 'ТаскРэббит', 'услуги', 'помощь'] },
    { url: 'https://thumbtack.com', title: 'Thumbtack', description: 'Платформа для поиска специалистов.', keywords: ['Thumbtack', 'Тамбтэк', 'услуги', 'специалисты'] },
    { url: 'https://rocket.chat', title: 'Rocket.Chat', description: 'Открытая платформа для чатов.', keywords: ['Rocket.Chat', 'Рокет Чат', 'мессенджер', 'команды'] },
    { url: 'https://cnn.com', title: 'CNN', description: 'Мировые новости и аналитика.', keywords: ['CNN', 'СиЭнЭн', 'новости', 'медиа'] },
    { url: 'https://bbc.com', title: 'BBC', description: 'Британские и мировые новости.', keywords: ['BBC', 'БиБиСи', 'новости', 'медиа'] },
    { url: 'https://forbes.com', title: 'Forbes', description: 'Новости бизнеса и финансов.', keywords: ['Forbes', 'Форбс', 'бизнес', 'новости'] },
    { url: 'https://discord.com', title: 'Discord', description: 'Мессенджер для геймеров и сообществ.', keywords: ['Discord', 'Дискорд', 'мессенджер', 'геймеры'] },
    { url: 'https://slack.com', title: 'Slack', description: 'Платформа для командного общения.', keywords: ['Slack', 'Слэк', 'мессенджер', 'работа'] },
    { url: 'https://notion.so', title: 'Notion', description: 'Платформа для заметок и проектов.', keywords: ['Notion', 'Ноушн', 'заметки', 'проекты'] },
    { url: 'https://figma.com', title: 'Figma', description: 'Инструмент для дизайна интерфейсов.', keywords: ['Figma', 'Фигма', 'дизайн', 'UI'] },
    { url: 'https://miro.com', title: 'Miro', description: 'Онлайн-доска для совместной работы.', keywords: ['Miro', 'Миро', 'доска', 'команда'] },
    { url: 'https://asana.com', title: 'Asana', description: 'Инструмент для управления задачами.', keywords: ['Asana', 'Асана', 'задачи', 'проекты'] },
    { url: 'https://grammarly.com', title: 'Grammarly', description: 'Инструмент для проверки текста.', keywords: ['Grammarly', 'Граммарли', 'текст', 'грамматика'] },
    { url: 'https://proton.me', title: 'Proton', description: 'Сервисы для приватности (почта, VPN).', keywords: ['Proton', 'Протон', 'почта', 'VPN'] },
    { url: 'https://xs-corp.github.io/ag-search/', title: 'AG Search', description: 'Вы же уже здесь находитесь, разве нет.....?', keywords: ['AG Search', 'AG', 'поиск', 'эйджи'] },
    { url: 'https://store.steampowered.com', title: 'Steam', description: 'Крупнейший игровой магазин.', keywords: ['Steam', 'Стим', 'игры', 'магазин'] },
    { url: 'https://ag-mini-ai.github.io/AG-AI-mini/', title: 'AG AI Mini', description: 'Ваш персональный мини-ии ассистент.', keywords: ['AG AI', 'AG', 'ии', 'эйджи'] },
    { url: 'https://movielab.one', title: 'Movielab', description: 'Лучший пиратский сервис для просмотра фильмов и сериалов.', keywords: ['Movielab', 'Мувилаб', 'торрент', 'фильмы', 'сериалы'] },
    { url: 'https://khanacademy.org', title: 'Khan Academy', description: 'Бесплатные онлайн-курсы по различным предметам.', keywords: ['Khan Academy', 'образование', 'курсы', 'учеба'] },
    { url: 'https://mit.edu', title: 'MIT OpenCourseWare', description: 'Бесплатные материалы курсов от MIT.', keywords: ['MIT', 'образование', 'курсы', 'университет'] },
    { url: 'https://stanford.edu', title: 'Stanford Online', description: 'Онлайн-курсы от Стэнфордского университета.', keywords: ['Stanford', 'образование', 'курсы', 'университет'] },
    { url: 'https://jstor.org', title: 'JSTOR', description: 'Библиотека академических журналов и книг.', keywords: ['JSTOR', 'наука', 'журналы', 'исследования'] },
    { url: 'https://pubmed.ncbi.nlm.nih.gov', title: 'PubMed', description: 'База данных медицинских исследований.', keywords: ['PubMed', 'медицина', 'исследования', 'здоровье'] },
    { url: 'https://nature.com', title: 'Nature', description: 'Научный журнал с исследованиями.', keywords: ['Nature', 'наука', 'журнал', 'исследования'] },
    { url: 'https://sciencedirect.com', title: 'ScienceDirect', description: 'Платформа научных публикаций.', keywords: ['ScienceDirect', 'наука', 'публикации', 'журналы'] },
    { url: 'https://springer.com', title: 'Springer', description: 'Издательство научных книг и журналов.', keywords: ['Springer', 'наука', 'книги', 'журналы'] },
    { url: 'https://ieee.org', title: 'IEEE', description: 'Ресурсы по инженерии и технологиям.', keywords: ['IEEE', 'технологии', 'инженерия', 'исследования'] },
    { url: 'https://acm.org', title: 'ACM Digital Library', description: 'Библиотека по информатике.', keywords: ['ACM', 'информатика', 'технологии', 'исследования'] },
    { url: 'https://ted.com', title: 'TED Talks', description: 'Вдохновляющие лекции на разные темы.', keywords: ['TED', 'лекции', 'образование', 'вдохновение'] },
    { url: 'https://nasa.gov', title: 'NASA', description: 'Официальный сайт NASA с новостями космоса.', keywords: ['NASA', 'космос', 'наука', 'исследования'] },
    { url: 'https://space.com', title: 'Space.com', description: 'Новости и статьи о космосе.', keywords: ['Space', 'космос', 'новости', 'наука'] },
    { url: 'https://esa.int', title: 'ESA', description: 'Сайт Европейского космического агентства.', keywords: ['ESA', 'космос', 'наука', 'Европа'] },
    { url: 'https://cern.ch', title: 'CERN', description: 'Сайт Европейской организации ядерных исследований.', keywords: ['CERN', 'физика', 'наука', 'исследования'] },
    { url: 'https://seti.org', title: 'SETI Institute', description: 'Исследования внеземной жизни.', keywords: ['SETI', 'космос', 'наука', 'жизнь'] },
    { url: 'https://edx.org', title: 'edX', description: 'Онлайн-курсы от ведущих университетов.', keywords: ['edX', 'образование', 'курсы', 'университеты'] },
    { url: 'https://futurelearn.com', title: 'FutureLearn', description: 'Бесплатные курсы от университетов.', keywords: ['FutureLearn', 'образование', 'курсы', 'учеба'] },
    { url: 'https://alison.com', title: 'Alison', description: 'Бесплатные онлайн-курсы.', keywords: ['Alison', 'образование', 'курсы', 'учеба'] },
    { url: 'https://udacity.com', title: 'Udacity', description: 'Курсы по технологиям и программированию.', keywords: ['Udacity', 'программирование', 'курсы', 'технологии'] },
    { url: 'https://skillshare.com', title: 'Skillshare', description: 'Курсы по творчеству и дизайну.', keywords: ['Skillshare', 'творчество', 'курсы', 'дизайн'] },
    { url: 'https://masterclass.com', title: 'MasterClass', description: 'Курсы от экспертов в разных областях.', keywords: ['MasterClass', 'курсы', 'эксперты', 'обучение'] },
    { url: 'https://pluralsight.com', title: 'Pluralsight', description: 'Курсы по IT и программированию.', keywords: ['Pluralsight', 'IT', 'программирование', 'курсы'] },
    { url: 'https://codecademy.com', title: 'Codecademy', description: 'Интерактивные курсы программирования.', keywords: ['Codecademy', 'программирование', 'курсы', 'код'] },
    { url: 'https://freecodecamp.org', title: 'freeCodeCamp', description: 'Бесплатное обучение программированию.', keywords: ['freeCodeCamp', 'программирование', 'курсы', 'бесплатно'] },
    { url: 'https://leetcode.com', title: 'LeetCode', description: 'Платформа для практики программирования.', keywords: ['LeetCode', 'программирование', 'задачи', 'код'] },
    { url: 'https://hackerrank.com', title: 'HackerRank', description: 'Платформа для coding-соревнований.', keywords: ['HackerRank', 'программирование', 'соревнования', 'код'] },
    { url: 'https://codewars.com', title: 'Codewars', description: 'Тренировка навыков программирования.', keywords: ['Codewars', 'программирование', 'задачи', 'код'] },
    { url: 'https://kaggle.com', title: 'Kaggle', description: 'Платформа для анализа данных и машинного обучения.', keywords: ['Kaggle', 'данные', 'машинное обучение', 'анализ'] },
    { url: 'https://datacamp.com', title: 'DataCamp', description: 'Курсы по анализу данных и Python.', keywords: ['DataCamp', 'данные', 'Python', 'курсы'] },
    { url: 'https://tableau.com', title: 'Tableau', description: 'Инструмент для визуализации данных.', keywords: ['Tableau', 'данные', 'визуализация', 'аналитика'] },
    { url: 'https://powerbi.microsoft.com', title: 'Power BI', description: 'Платформа для бизнес-аналитики.', keywords: ['Power BI', 'аналитика', 'данные', 'Microsoft'] },
    { url: 'https://rapidapi.com', title: 'RapidAPI', description: 'Платформа для работы с API.', keywords: ['RapidAPI', 'API', 'программирование', 'разработка'] },
    { url: 'https://postman.com', title: 'Postman', description: 'Инструмент для тестирования API.', keywords: ['Postman', 'API', 'тестирование', 'разработка'] },
    { url: 'https://zapier.com', title: 'Zapier', description: 'Автоматизация рабочих процессов.', keywords: ['Zapier', 'автоматизация', 'работа', 'инструменты'] },
    { url: 'https://ifttt.com', title: 'IFTTT', description: 'Автоматизация задач через сценарии.', keywords: ['IFTTT', 'автоматизация', 'задачи', 'инструменты'] },
    { url: 'https://airtable.com', title: 'Airtable', description: 'Инструмент для управления проектами и данными.', keywords: ['Airtable', 'проекты', 'данные', 'управление'] },
    { url: 'https://monday.com', title: 'Monday.com', description: 'Платформа для управления командами.', keywords: ['Monday', 'проекты', 'управление', 'команды'] },
    { url: 'https://clickup.com', title: 'ClickUp', description: 'Инструмент для управления задачами.', keywords: ['ClickUp', 'задачи', 'управление', 'проекты'] },
    { url: 'https://flightradar24.com', title: 'Flightradar24', description: 'Отслеживание полётов в реальном времени.', keywords: ['Flightradar24', 'авиация', 'полёты', 'отслеживание'] },
    { url: 'https://seatguru.com', title: 'SeatGuru', description: 'Информация о местах в самолётах.', keywords: ['SeatGuru', 'авиация', 'путешествия', 'полёты'] },
    { url: 'https://rome2rio.com', title: 'Rome2rio', description: 'Планирование маршрутов путешествий.', keywords: ['Rome2rio', 'путешествия', 'маршруты', 'план'] },
    { url: 'https://wanderlog.com', title: 'Wanderlog', description: 'Планировщик путешествий.', keywords: ['Wanderlog', 'путешествия', 'план', 'маршруты'] },
    { url: 'https://nomadlist.com', title: 'Nomad List', description: 'Ресурс для цифровых кочевников.', keywords: ['Nomad List', 'путешествия', 'работа', 'номады'] },
    { url: 'https://workaway.info', title: 'Workaway', description: 'Платформа для волонтёрства и путешествий.', keywords: ['Workaway', 'путешествия', 'волонтёрство', 'работа'] },
    { url: 'https://couchsurfing.com', title: 'Couchsurfing', description: 'Сообщество для путешественников.', keywords: ['Couchsurfing', 'путешествия', 'сообщество', 'гостеприимство'] },
    { url: 'https://hostelworld.com', title: 'Hostelworld', description: 'Бронирование хостелов по всему миру.', keywords: ['Hostelworld', 'путешествия', 'хостелы', 'бронирование'] },
    { url: 'https://hipcamp.com', title: 'Hipcamp', description: 'Бронирование кемпингов.', keywords: ['Hipcamp', 'путешествия', 'кемпинг', 'туризм'] },
    { url: 'https://nationalgeographic.com', title: 'National Geographic', description: 'Журнал о природе и путешествиях.', keywords: ['National Geographic', 'природа', 'путешествия', 'наука'] },
    { url: 'https://atlasobscura.com', title: 'Atlas Obscura', description: 'Необычные места и истории.', keywords: ['Atlas Obscura', 'путешествия', 'истории', 'места'] },
    { url: 'https://roadsideamerica.com', title: 'Roadside America', description: 'Гид по необычным достопримечательностям США.', keywords: ['Roadside America', 'путешествия', 'достопримечательности', 'США'] },
    { url: 'https://smithsonianmag.com', title: 'Smithsonian Magazine', description: 'Журнал о науке и культуре.', keywords: ['Smithsonian', 'наука', 'культура', 'журнал'] },
    { url: 'https://britannica.com', title: 'Britannica', description: 'Онлайн-энциклопедия.', keywords: ['Britannica', 'энциклопедия', 'знания', 'образование'] },
    { url: 'https://howstuffworks.com', title: 'HowStuffWorks', description: 'Объяснения сложных тем простым языком.', keywords: ['HowStuffWorks', 'образование', 'знания', 'объяснения'] },
    { url: 'https://investopedia.com', title: 'Investopedia', description: 'Ресурс о финансах и инвестициях.', keywords: ['Investopedia', 'финансы', 'инвестиции', 'образование'] },
    { url: 'https://morningstar.com', title: 'Morningstar', description: 'Финансовый анализ и инвестиции.', keywords: ['Morningstar', 'финансы', 'инвестиции', 'аналитика'] },
    { url: 'https://fool.com', title: 'The Motley Fool', description: 'Советы по инвестициям и финансам.', keywords: ['Motley Fool', 'финансы', 'инвестиции', 'советы'] },
    { url: 'https://bloomberg.com', title: 'Bloomberg', description: 'Финансовые новости и аналитика.', keywords: ['Bloomberg', 'финансы', 'новости', 'аналитика'] },
    { url: 'https://wsj.com', title: 'The Wall Street Journal', description: 'Новости бизнеса и финансов.', keywords: ['Wall Street Journal', 'финансы', 'новости', 'бизнес'] },
    { url: 'https://ft.com', title: 'Financial Times', description: 'Мировые финансовые новости.', keywords: ['Financial Times', 'финансы', 'новости', 'бизнес'] },
    { url: 'https://reuters.com', title: 'Reuters', description: 'Международные новости и аналитика.', keywords: ['Reuters', 'новости', 'аналитика', 'медиа'] },
    { url: 'https://guardian.co.uk', title: 'The Guardian', description: 'Британская газета с новостями.', keywords: ['Guardian', 'новости', 'медиа', 'Великобритания'] },
    { url: 'https://washingtonpost.com', title: 'The Washington Post', description: 'Американские и мировые новости.', keywords: ['Washington Post', 'новости', 'медиа', 'США'] },
    { url: 'https://latimes.com', title: 'Los Angeles Times', description: 'Новости Калифорнии и мира.', keywords: ['Los Angeles Times', 'новости', 'медиа', 'США'] },
    { url: 'https://chicagotribune.com', title: 'Chicago Tribune', description: 'Новости Чикаго и США.', keywords: ['Chicago Tribune', 'новости', 'медиа', 'США'] },
    { url: 'https://usatoday.com', title: 'USA Today', description: 'Национальные новости США.', keywords: ['USA Today', 'новости', 'медиа', 'США'] },
    { url: 'https://nypost.com', title: 'New York Post', description: 'Новости Нью-Йорка и США.', keywords: ['New York Post', 'новости', 'медиа', 'США'] },
    { url: 'https://theatlantic.com', title: 'The Atlantic', description: 'Журнал о политике и культуре.', keywords: ['The Atlantic', 'новости', 'культура', 'политика'] },
    { url: 'https://newyorker.com', title: 'The New Yorker', description: 'Журнал о культуре и литературе.', keywords: ['New Yorker', 'культура', 'литература', 'журнал'] },
    { url: 'https://rollingstone.com', title: 'Rolling Stone', description: 'Журнал о музыке и поп-культуре.', keywords: ['Rolling Stone', 'музыка', 'культура', 'журнал'] },
    { url: 'https://pitchfork.com', title: 'Pitchfork', description: 'Музыкальные новости и обзоры.', keywords: ['Pitchfork', 'музыка', 'новости', 'обзоры'] },
    { url: 'https://billboard.com', title: 'Billboard', description: 'Музыкальные чарты и новости.', keywords: ['Billboard', 'музыка', 'чарты', 'новости'] },
    { url: 'https://metacritic.com', title: 'Metacritic', description: 'Обзоры фильмов, игр и музыки.', keywords: ['Metacritic', 'обзоры', 'игры', 'фильмы'] },
    { url: 'https://rottentomatoes.com', title: 'Rotten Tomatoes', description: 'Рейтинги и обзоры фильмов.', keywords: ['Rotten Tomatoes', 'фильмы', 'обзоры', 'рейтинги'] },
    { url: 'https://imdb.com', title: 'IMDb', description: 'База данных фильмов и сериалов.', keywords: ['IMDb', 'фильмы', 'сериалы', 'кино'] },
    { url: 'https://letterboxd.com', title: 'Letterboxd', description: 'Социальная сеть для любителей кино.', keywords: ['Letterboxd', 'кино', 'соцсеть', 'фильмы'] },
    { url: 'https://goodreads.com', title: 'Goodreads', description: 'Сообщество для любителей книг.', keywords: ['Goodreads', 'книги', 'чтение', 'соцсеть'] },
    { url: 'https://archive.org', title: 'Internet Archive', description: 'Архив интернета и цифровых данных.', keywords: ['Internet Archive', 'архив', 'данные', 'интернет'] },
    { url: 'https://gutenberg.org', title: 'Project Gutenberg', description: 'Бесплатные электронные книги.', keywords: ['Gutenberg', 'книги', 'чтение', 'бесплатно'] },
    { url: 'https://openlibrary.org', title: 'Open Library', description: 'Открытая библиотека книг.', keywords: ['Open Library', 'книги', 'библиотека', 'чтение'] },
    { url: 'https://z-lib.is', title: 'Z-Library', description: 'Библиотека электронных книг и статей.', keywords: ['Z-Library', 'книги', 'библиотека', 'чтение'] },
    { url: 'https://sci-hub.se', title: 'Sci-Hub', description: 'Доступ к научным статьям.', keywords: ['Sci-Hub', 'наука', 'статьи', 'исследования'] },
    { url: 'https://scholar.google.com', title: 'Google Scholar', description: 'Поиск академических публикаций.', keywords: ['Google Scholar', 'наука', 'публикации', 'исследования'] },
    { url: 'https://researchgate.net', title: 'ResearchGate', description: 'Социальная сеть для учёных.', keywords: ['ResearchGate', 'наука', 'учёные', 'исследования'] },
    { url: 'https://academia.edu', title: 'Academia.edu', description: 'Платформа для научных работ.', keywords: ['Academia', 'наука', 'публикации', 'исследования'] },
    { url: 'https://orcid.org', title: 'ORCID', description: 'Идентификаторы для исследователей.', keywords: ['ORCID', 'наука', 'исследователи', 'идентификаторы'] },
    { url: 'https://mendeley.com', title: 'Mendeley', description: 'Инструмент для управления научными статьями.', keywords: ['Mendeley', 'наука', 'статьи', 'исследования'] },
    { url: 'https://zotero.org', title: 'Zotero', description: 'Менеджер библиографических ссылок.', keywords: ['Zotero', 'наука', 'библиография', 'исследования'] },
    { url: 'https://overleaf.com', title: 'Overleaf', description: 'Онлайн-редактор LaTeX.', keywords: ['Overleaf', 'LaTeX', 'наука', 'документы'] },
    { url: 'https://mathworks.com', title: 'MathWorks', description: 'MATLAB и Simulink для инженерии.', keywords: ['MathWorks', 'MATLAB', 'инженерия', 'софт'] },
    { url: 'https://wolfram.com', title: 'Wolfram', description: 'Инструменты для вычислений и исследований.', keywords: ['Wolfram', 'вычисления', 'наука', 'исследования'] },
    { url: 'https://sagepub.com', title: 'SAGE Publishing', description: 'Издательство академических журналов.', keywords: ['SAGE', 'наука', 'журналы', 'публикации'] },
    { url: 'https://tandfonline.com', title: 'Taylor & Francis', description: 'Платформа научных публикаций.', keywords: ['Taylor & Francis', 'наука', 'публикации', 'журналы'] },
    { url: 'https://wiley.com', title: 'Wiley', description: 'Издательство научных книг и журналов.', keywords: ['Wiley', 'наука', 'книги', 'журналы'] },
    { url: 'https://elsevier.com', title: 'Elsevier', description: 'Издательство научной литературы.', keywords: ['Elsevier', 'наука', 'публикации', 'журналы'] },
    { url: 'https://icloud.com', title: 'iCloud', description: 'Облачный сервис от Apple.', keywords: ['iCloud', 'айклауд', 'Apple', 'облако'] }
];

export default siteIndex;
